export { default as registerComponents } from './register'

export { default as Example1Chart } from './Example1Chart.vue'
export { default as Example2Chart } from './Example2Chart.vue'
export { default as Example3Chart } from './Example3Chart.vue'
export { default as Example4Chart } from './Example4Chart.vue'
export { default as Example5Chart } from './Example5Chart.vue'
export { default as Example6Chart } from './Example6Chart.vue'
export { default as Example7Chart } from './Example7Chart.vue'
export { default as Example8Chart } from './Example8Chart.vue'
export { default as Example9Chart } from './Example9Chart.vue'
export { default as Example10Chart } from './Example10Chart.vue'
export { default as Example11Chart } from './Example11Chart.vue'
